{% set version = "0.3.4" %}

package:
  name: ezc3d
  version: {{ version }}

source:
  fn: {{ version }}.tar.gz
  url: https://github.com/pyomeca/ezc3d/archive/Release_{{ version }}.tar.gz
  sha256: e3df9ad0fc106b271c39e5e63e1f82f92061d0a68bd3689a783bb2641848c266

build:
  skip: True  # [py2k or osx]
  number: 0
  rpaths:
    - lib/
    - lib/ezc3d/


requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - swig
  host:
    - python
    - numpy
  run:
    - python
    - {{ pin_compatible('numpy') }}


test:
  imports:
    - ezc3d

about:
  home: https://github.com/pyomeca/ezc3d
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Easy to use C3D reader/writer in C++, Python'

  description: |
    EZC3D is an easy to use reader, modifier and writer for C3D format files. It
    is written en C++ with proper binders for Python and MATLAB scripting
    langages.

  doc_url: https://pyomeca.github.io/Documentation/ezc3d/
  dev_url: https://github.com/pyomeca/ezc3d

extra:
  recipe-maintainers:
    - melund
