{% set name = "ezc3d" %}
{% set version = "1.5.10" %}
{% set build_num = 0 %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/pyomeca/{{ name }}/archive/Release_{{ version }}.tar.gz
  sha256: c200c102ce845b9560eddcc0bd709b832da8e3332f7fa150d9cabd4a5e27da2a

build:
  number: {{ build_num }}
  rpaths:
    - lib/
    - lib/{{ name }}/
  run_exports:
    - {{ pin_subpackage('ezc3d', max_pin='x.x') }}
    - {{ name }} * *{ backend }}_*
  skip: true  # [py<310]
  skip: true  # [arm64 and backend == "octave"]
  string: py{{ py }}_{{ backend }}_h{{ PKG_HASH }}_{{ build_num }}
  track_features:
    - octave  # [backend == "octave"]
requirements:
  build:
    - cmake
    - ninja
    - pkgconfig
    - swig
    - python                                 # [build_platform != target_platform and backend == "python3"]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform and backend == "python3"]
    - numpy                                  # [build_platform != target_platform and backend == "python3"]
    - octave                                 # [backend == "octave"]
    - {{ compiler('cxx') }}
  host:
    - python   # [backend == "python3"]
    - numpy    # [backend == "python3"]
    - octave   # [backend == "octave"]
  run:
    - python                          # [backend == "python3"]
    - {{ pin_compatible('numpy') }}   # [backend == "python3"]
    - octave                          # [backend == "octave"]

test:
  imports:
    - ezc3d  # [backend == "python3"]

about:
  home: https://github.com/pyomeca/ezc3d
  license: MIT
  license_file: LICENSE
  summary: Easy to use C3D reader/writer in C++, Python

  description: |
    EZC3D is an easy to use reader, modifier and writer for C3D format files. It
    is written en C++ with proper binders for Python and MATLAB scripting
    langages.

  doc_url: https://pyomeca.github.io/Documentation/ezc3d/
  dev_url: https://github.com/pyomeca/ezc3d

extra:
  recipe-maintainers:
    - melund
    - pariterre
