{% set version = "1.4.1" %}

package:
  name: ezc3d
  version: {{ version }}

source:
  fn: {{ version }}.tar.gz
  url: https://github.com/pyomeca/ezc3d/archive/Release_{{ version }}.tar.gz
  sha256: 0cc9cd71558d6ddfd2c66dc43fa0501ffd7f5806334ef86483a2a930c7884061

build:
  skip: true  # [py2k]
  number: 0
  rpaths:
    - lib/
    - lib/ezc3d/
  run_exports:
    - {{ pin_subpackage('ezc3d', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - swig
    - ninja  # [win]
  host:
    - python
    - numpy
  run:
    - python
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - ezc3d

about:
  home: https://github.com/pyomeca/ezc3d
  license: MIT
  license_file: LICENSE
  summary: Easy to use C3D reader/writer in C++, Python

  description: |
    EZC3D is an easy to use reader, modifier and writer for C3D format files. It
    is written en C++ with proper binders for Python and MATLAB scripting
    langages.

  doc_url: https://pyomeca.github.io/Documentation/ezc3d/
  dev_url: https://github.com/pyomeca/ezc3d

extra:
  recipe-maintainers:
    - melund
    - pariterre
