{% set name = ezc3d %}
{% set version = "1.5.1" %}
{% set build_num = 4 %}

package:
  name: ezc3d
  version: {{ version }}

source:
  fn: {{ version }}.tar.gz
  url: https://github.com/pyomeca/{{ name }}/archive/Release_{{ version }}.tar.gz
  sha256: e7041e71cd1c195d6cf5e3fc22ff8c703f1ab8b24dbbc3832c571034d61df467

build:
  number: {{ build_num }}
  rpaths:
    - lib/
    - lib/{{ name }}/
  run_exports:
    - {{ pin_subpackage('ezc3d', max_pin='x.x') }}
  skip: true  # [py<39]
requirements:
  build:
    - cmake
    - ninja
    - pkgconfig
    - swig
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('cxx') }}
  host:
    - python
    - numpy
  run:
    - python
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - ezc3d  # [backend == "python3"]

about:
  home: https://github.com/pyomeca/ezc3d
  license: MIT
  license_file: LICENSE
  summary: Easy to use C3D reader/writer in C++, Python

  description: |
    EZC3D is an easy to use reader, modifier and writer for C3D format files. It
    is written en C++ with proper binders for Python and MATLAB scripting
    langages.

  doc_url: https://pyomeca.github.io/Documentation/ezc3d/
  dev_url: https://github.com/pyomeca/ezc3d

extra:
  recipe-maintainers:
    - melund
    - pariterre
