{% set version = "1.2.3" %}

package:
  name: ezc3d
  version: {{ version }}

source:
  fn: {{ version }}.tar.gz
  url: https://github.com/pyomeca/ezc3d/archive/Release_{{ version }}.tar.gz
  sha256: e7ea61c7ccd5014de25e0c63fe1081aa20c333f06d0c9bc805ce472fe76970be

build:
  skip: True  # [py2k]
  number: 0
  rpaths:
    - lib/
    - lib/ezc3d/


requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - swig
    - jom  # [win]
  host:
    - python
    - numpy
  run:
    - python
    - {{ pin_compatible('numpy') }}


test:
  imports:
    - ezc3d

about:
  home: https://github.com/pyomeca/ezc3d
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Easy to use C3D reader/writer in C++, Python'

  description: |
    EZC3D is an easy to use reader, modifier and writer for C3D format files. It
    is written en C++ with proper binders for Python and MATLAB scripting
    langages.

  doc_url: https://pyomeca.github.io/Documentation/ezc3d/
  dev_url: https://github.com/pyomeca/ezc3d

extra:
  recipe-maintainers:
    - melund
    - pariterre
