{% set version = "1.5.1" %}
{% set build_num = 4 %}

package:
  name: ezc3d
  version: {{ version }}

source:
  fn: {{ version }}.tar.gz
  url: https://github.com/pyomeca/ezc3d/archive/Release_{{ version }}.tar.gz
  sha256: e7041e71cd1c195d6cf5e3fc22ff8c703f1ab8b24dbbc3832c571034d61df467

build:
  skip: true  # [py<39]
  number: 0
  rpaths:
    - lib/
    - lib/ezc3d/
  run_exports:
    - {{ pin_subpackage('ezc3d', max_pin='x.x') }}
    - ezc3d * {{ backend }}_*
  string: py{{ py }}_{{ backend }}_h{{ PKG_HASH }}_{{ build_num }}
  track_features:
    - octave  # [backend == "octave"]

requirements:
  build:
    - cmake
    - swig
    - pkgconfig
    - python  # [build_platform != target_platform]
    - numpy  # [build_platform != target_platform]
    - ninja 
    - {{ compiler('cxx') }}
  host:
    - python  # [backend == "python3"]
    - numpy   # [backend == "python3"]
    - octave  # [backend == "octave"]
  run:
    - python  # [backend == "python3"]
    - {{ pin_compatible('numpy') }}  # [backend == "python3"]
    - octave  # [backend == "octave"]

test:
  imports:
    - ezc3d  # [backend == "python3"]

about:
  home: https://github.com/pyomeca/ezc3d
  license: MIT
  license_file: LICENSE
  summary: Easy to use C3D reader/writer in C++, Python

  description: |
    EZC3D is an easy to use reader, modifier and writer for C3D format files. It
    is written en C++ with proper binders for Python and MATLAB scripting
    langages.

  doc_url: https://pyomeca.github.io/Documentation/ezc3d/
  dev_url: https://github.com/pyomeca/ezc3d

extra:
  recipe-maintainers:
    - melund
    - pariterre
