appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
travis:
  secure: {BINSTAR_TOKEN: EwZm8QI36EdSpy4UJ5zYgh9v+Gw+zTjIvZgUAyG2fGjh5NeMMZtrf7HDbm5p4XRcL4zxHCUU2Ojpp9Mx6szmnpcQpzOGsd9Skjb53PbZobFZIqVkKnybzZ1W5lCI8OYdIerPaEu6VRUIM+lpnm+/MxLdluJnF8g6q3yVO+d5TsYPdskH3hqJlkbkIP0GQLU2kLmVILLAL2fVeSCDCLVEtA0AzZGsvW7ToYti3MwAssh9nCn/NqhHRzAwRW0RH9tRdFJV5Rd8d8VuZwXW0OGGaHEqV19VMlyDdI1+GWnC+0qpJuApVMfMjKhCHV82YuwgUMvzxW0xkjK0VVDHc2SHWS9Xt1lOSeBTger6FN5fyv7zcb+/tZQdCsB+AnWDaqf6Tnidf4MSRJV5IMdBYIf3xbZNyh0BbM8wBV/1zd2AE4LpoFEYh2MtuEijh9lXy1mgdGm0cTKVv79u5m4AlSI/0LIsrzVgQaAziec6OGfd9BOq/QCDwJ/YuKX8C8B3T9H5Bzu7GkBYRPCARLLemJ+9a7J0RDz56CPF2o8pJX1QpM6rol8yfQBt9KWcUuHVy3te8v57r4qwBS6YyfL3FerywVS290uW74QX8mACF6KsiIkS+Vsxu274BM9V/QlPfXU0oWl1sP2pgZCsdGb4nuHSAKD/Au+Cputhl/+O9Cxy8hk=}
conda_forge_output_validation: true
bot:
  automerge: true
